name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }} # Add your Docker Hub username as a secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Add your Docker Hub password or personal access token as a secret

      - name: Build Docker image
        run: |
          docker build -t alexischartier/back-testci:latest .

      - name: Push Docker image
        run: |
          docker push alexischartier/back-testci:latest
