name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optionnel : Installer une version spécifique de Java (ici JDK 21, à adapter selon vos besoins)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # Construire l'application Quarkus avec Gradle
      - name: Build Quarkus Application
        run: ./gradlew clean quarkusBuild

      # Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker en utilisant le Dockerfile.jvm de Quarkus
      - name: Build Docker image using Dockerfile.jvm
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t alexischartier/back-testci:latest .

      # Pousser l'image Docker sur Docker Hub
      - name: Push Docker image
        run: docker push alexischartier/back-testci:latest
